services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: final
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - alfred_app_default

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi_backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:admin@postgres_db:5432/final
      STORE_DATABASE_URL: postgresql://postgres:admin@postgres_db:5432/final
      OPENAI_API_KEY: sk-proj-zgXqKiXJ3flv7xFoBvdjT3BlbkFJ1hezS1kRuOsw0jTkBEjE
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - alfred_app_default

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: http://localhost:8000
    container_name: react_frontend

    ports:
      - "3000:80"
    depends_on:
      - backend


volumes:
  postgres_data:

networks:
  alfred_app_default:  # Define the network here
    driver: bridge