services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi_backend
    environment:
      DATABASE_URL: postgresql+asyncpg://myuser:mypassword@db:5432/mydb
      STORE_DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydb
      OPENAI_API_KEY: sk-proj-R9wyNrcI90lJDpXWx37uT3BlbkFJTXbYarJRiFJ5zkYNzV4h
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react_frontend
    environment:
      API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
