services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: alfred
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi_backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:admin@localhost:5432/alfred
      STORE_DATABASE_URL: postgresql://postgres:admin@localhost:5432/alfred
      OPENAI_API_KEY: sk-proj-zgXqKiXJ3flv7xFoBvdjT3BlbkFJ1hezS1kRuOsw0jTkBEjE
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: http://localhost:8000
    container_name: react_frontend

    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
